### ISSUE TITLE
Image arithmetic not handing NaNs / blanks correctly

### ISSUE THREAD

**Issue by IanHeywood** [ratt-ru/tigger#129]
I just tried to do a quick primary beam correction on an ATCA image using the 'compute image' (b/a) function. The result should be blanked in the regions where the beam image is (something / NaN = NaN), but the original image values are preserved instead.

![Screen Shot 2021-11-02 at 17 03 36](https://user-images.githubusercontent.com/6533799/139911973-f3bddd6e-f5d1-4d87-9257-b0c697fee631.png)

**Comment by razman786** [comment]
@IanHeywood - could you send some test files for me to replicate the issue please?

**Comment by razman786** [comment]
@IanHeywood - I've failed to replicate this bug. I have however verified Tigger's numpy et al code in branch 'version_161', even against version 1.5.1, just to make sure nothing has crept in. Therefore, I will close this bug for now. 

Please try to replicate the issue with branch 'version_161' and if the same issue arises please re-open this issue.
