### ISSUE TITLE
KERN-suite inclusion status

### ISSUE THREAD

**Issue by kwazzi-jack** [ratt-ru/tigger#150]
Hi, thought this might be helpful as it caused me a bit of a head spin and took awhile to figure out. Is it possible to add an indicator to the repository page that displays whether or not `tigger` is currently included in a specific KERN repository? That way it would be more clear whether to install via package-managers and KERN, install manually, or try a different KERN repository.

As far as I could find out, the status of `tigger` in the different KERNs at the time of this post is:
- KERN-8: Missing
- KERN-7: Present
- KERN-6: Present
- KERN-5: Present
- KERN-4: Present
- KERN-3: Present
- KERN-dev: Present

**Comment by Athanaseus** [comment]
Thanks for the issue @kwazzi-jack.
I have updated the README to specify the KERN version #151.
`tigger-1.6.1.1` should now be available for KERN-8.

**Comment by kwazzi-jack** [comment]
Thank you!
