### ISSUE TITLE
custom plot styles havoc

### ISSUE THREAD

**Issue by gijzelaerr** [ratt-ru/tigger#36]
##### at 2012-06-04 16:09:13 Oleg Smirnov reported:

custom plot styles havoc

**Comment by razman786** [comment]
@gijzelaerr - I'm trying to reproduce this error in v1.6.0 of tigger. I have a 3C147 model file, but I'm not sure if it is the same one that you reference as being from the Users Guide. If I try and follow the steps above, I cannot reproduce the issue, or I've misunderstood. Can you please clarify if this is still an issue with v1.6.0 of tigger?

**Comment by razman786** [comment]
Closing and marking as stale, due to lack of activity.
