### ISSUE TITLE
tigger-restore does not handle frequency properly for image cubes

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/tigger#46]
tigger-restore currently uses a single frequency value (for spectral index and PB) when computing the restoring fluxes. While this is semi-OK-ish for a single frequency image (which is all we've been using it with for now), provided the frequency is set correctly (currently taken from LSM or from command line -- **this is wrong** -- need to take it from image header), for a cube it won't do at all.

**Comment by razman786** [comment]
Closing and marking as stale, due to lack of activity.
