### ISSUE TITLE
RM values not being displayed properly

### ISSUE THREAD

**Issue by modhurita** [ratt-ru/tigger#57]
I am trying to display an RM-cube using tigger, and am getting this error:

> mitra@elwood:~/PrimaryBeamReduction/MultiChannel$ tigger P_RM.fits &
> [6] 18506
> mitra@elwood:~/PrimaryBeamReduction/MultiChannel$ Welcome to Tigger using svn version 
> Please wait a second while the GUI starts up.
> Loading image P_RM.fits
> /home/mitra/MeqTrees/tigger/Tigger/Images/SkyImage.py:449: RuntimeWarning: divide by zero encountered in long_scalars
>   ndigits = int(math.ceil(math.log10(max(abs(valarr))/abs((valarr[1:]-valarr[0:-1])).min())));
> /usr/lib/python2.7/dist-packages/numpy/ma/core.py:778: RuntimeWarning: invalid value encountered in greater_equal
>   return umath.absolute(a) \* self.tolerance >= umath.absolute(b)

The RM values should be from -500 to +500 rad/m<sup>2</sup>, in increments of 100 rad/m<sup>2</sup>, but I am seeing the slices being displayed as either -1 K rad/m<sup>2</sup> or 0 rad/m<sup>2</sup>.

The file is here: `elwood: /home/mitra/PrimaryBeamReduction/MultiChannel/P_RM.fits`.

Pinging @o-smirnov in case github doesn't send a notification

**Comment by razman786** [comment]
Closing and marking as stale, due to lack of activity.
