### ISSUE TITLE
tigger-restore flux of Gaussian model components out by 2pi

### ISSUE THREAD

**Issue by landmanbester** [ratt-ru/tigger#96]
Not sure if I'm missing something here @o-smirnov but when running tigger-restore on lsm's containing Gaussian sources it produces model images with total flux exactly 2pi times the flux specified in the lsm. I suppose this is the source of the factor of 2pi confusion I had with my resolve experiments in DDFacet. I've also been chasing ghosts trying to get my MS-clean models to match up with those produced by tigger-restore. That's what you get for blindly trusting software I guess. Is this a feature or a bug?

**Comment by o-smirnov** [comment]
> That's what you get for blindly trusting software

Indeed. Only the Pope is infallible!

It could well be a bug -- a 2pi factor is exactly the sort of thing one screws up easily when implementing Gaussians -- but I'm surprised nobody picked up on it earlier!

**Comment by razman786** [comment]
Closing and marking as stale, due to lack of activity.
